import random
import math
import statistics

def random_list(length):
    """
    Returns a list of random integers
    All integers are in the range [1, length]

    Parameters:
    length (type: int) - length of random list and upper bound (exclusive) for the random integers

    Returns:
    (type: list) the random list
    """
    
    list1 = []
    for i in range(length):
        rand = random.randint(1, length)
        list1.append(rand)
    return list1

def check_unique(input_list):
    """
    Checks if a list has all unique objects

    Parameters:
    input_list (type: list) - the list to check

    Returns:
    (type: boolean) whether the list contains all unique elements or not (ie: True means it's unique)
    """
    
    i = 0
    for item in input_list:
        if input_list.index(item) != i:
            return False
        i += 1
    return True

def chance_for_unq(length):
    """
    Calculates the chance of a list containing all unique elements based on constraints of random_list function
    eg: a list of length 10 containing integers in range of [1, 10]

    Parameters:
    length (type: int) - length of the list

    Returns:
    (type: float) the chance the list is all unique elements (eg: 0.1 means a 10% chance)
    """
    chance = 1
    for i in range(length):
        chance = chance * ((length - i)/length)
    return chance

def num_of_attempts(length):
    """
    Counts how many times it takes to get a list with all unique elements

    Parameters:
    length (type: int) - length of the list (generated by random_list function)

    Returns:
    (type: int) number of attempts
    """
    attempts = 0
    success = False
    while (not success):
        list_check = random_list(length)
        success = check_unique(list_check)
        attempts += 1
    return attempts

if __name__ == "__main__":
    length = 10
    expected_attempts = 1/chance_for_unq(length)

    list1 = []
    for i in range(100):
        list1.append(num_of_attempts(length))

    average_attempts = statistics.mean(list1)
    print(f"Average # of attempts: {average_attempts}")
    print(f"Expected # of attempts: {expected_attempts}")
    

